### ISSUE TITLE
How to get custom content, such as how many times to get docker restart

### ISSUE THREAD

**Issue by junly917** [monitoringartist/zabbix-agent-xxl#51] opened 2019-08-25 11:57 UTC
I want to get the restart times of the container. I have checked the docker API, but it seems that there is no parameter to get the restart times. Is there any other way to get it?

**Comment by jangaraj** [comment] 2019-08-25 21:36
That is request for support and not a bug report. I'm closing it. 
Idea: track start times, any change of start time = restart.

**Closed as completed by jangaraj** 2019-08-25 21:36 UTC
