### ISSUE TITLE
Zabbix / DockAgent issue

### ISSUE THREAD

**Issue by arturslogins** [monitoringartist/zabbix-agent-xxl#55] opened 2020-07-14 14:17 UTC
Hello, 

I came across with two problems: 
1. In agent container logs i see failed process, and i can't figure out, what's the problem it is .. 

 `
61:20200714:140428.312 execl() failed for [who | wc -l]: [2] No such file or directory
25:20200714:140428.312 Process exited with code: 1.
`

2. In Zabbix console, importing template, template status is showing, that it's not supported 
And info message is "Unsupported item key" 
 
![image](https://user-images.githubusercontent.com/9640414/87436464-c02c2780-c5f5-11ea-9423-0ab7f68e315e.png)
Zabbix version 4.2

**Comment by jangaraj** [comment] 2020-07-14 15:12
`execl() failed for [who | wc -l]` - You are importing/assigning template, which is not provided by this project. I guess you are using official Zabbix Agent template, where `who | wc -l` is used. Of course commands `wc, who` are not available in the dockbix-agent-xxl image, so they are failing.

`Unsupported item key` - check your dockbix-agent-xxl container logs, pls to see why `docker.discovery` is unsupported.

**Comment by arturslogins** [comment] 2020-07-14 15:14
Soled problem 1 

But get another 2 problems 

`
   18:20200714:151319.527 Cannot find the [Id] item in the received JSON object


    18:20200714:151319.527 Cannot open metric file: '/rootfs/sys/fs/cgroup/cpu,cpuacct/docker//dockbix-agent-xxl_dockbix-agent-xxl.1.pfwveqazjr8rzmqmhugon9ik5/cpuacct.stat'


    25:20200714:151333.035 Cannot find the [Id] item in the received JSON object


    25:20200714:151333.035 Cannot open metric file: '/rootfs/sys/fs/cgroup/memory/docker//dockbix-agent-xxl_dockbix-agent-xxl.1.pfwveqazjr8rzmqmhugon9ik5/memory.stat'

    20:20200714:151333.137 Cannot find the [Id] item in the received JSON object
`

**Comment by jangaraj** [comment] 2020-07-14 15:21
Please check the logs from the start. If discovery is not working correctly (maybe because you didn't read readme about permissions - I don't know), then all items will be requesting incorrect Id.

https://github.com/monitoringartist/dockbix-agent-xxl#support

**Comment by arturslogins** [comment] 2020-07-15 06:06
But these logs to docker container comes from Zabbix? 
What you mean about permissions?

**Comment by arturslogins** [comment] 2020-07-15 09:30
i would like to know, why i get this message in my logfile now: 


dockbix-agent-xxl_1  |     24:20200715:092546.471 Sending back [ZBX_NOTSUPPORTED: Cannot find a line with requested metric in memory.stat file]
dockbix-agent-xxl_1  |     24:20200715:092638.297 Sending back [ZBX_NOTSUPPORTED: Cannot find information for this network interface in /proc/net/dev.]
dockbix-agent-xxl_1  |     19:20200715:092639.489 Sending back [ZBX_NOTSUPPORTED: Cannot find information for this network interface in /proc/net/dev.]

**Comment by jangaraj** [comment] 2020-07-15 10:50
Sorry, I'm closing this issue, because you are not providing correct issue description. 

I recommend to read https://stackoverflow.com/help/how-to-ask

There can be milions reasons why you have problem, but you did not provide reproducible example, so you can't get answer and I'm not going to iterate all millions possible issues, which you may have.

**Closed as completed** 2020-07-15 10:50 UTC
